output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks_cluster.cluster_endpoint
}

output "cluster_ca_certificate_base64" {
  description = "Cluster CA Certificate Base64"
  value       = module.eks_cluster.cluster_ca_certificate_base64
}

output "cluster_token" {
  description = "Cluster Token"
  value       = module.eks_cluster.cluster_token
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks_cluster.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks_cluster.kubectl_config
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks_cluster.config_map_aws_auth
}

output "vpc_id" {
  description = "VPC Id"
  value       = module.network.vpc_id
}

output "private_subnets" {
  description = "Private Subnet Ids"
  value       = module.network.private_subnets
}

output "public_subnets" {
  description = "Public Subnet Ids"
  value       = module.network.public_subnets
}
